BEGIN;

CREATE TABLE auth_tokens (
  "userId" INTEGER NOT NULL,
  selector CHAR(36) NOT NULL,
  validator CHAR(60) NOT NULL,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("userId", selector)
);

CREATE TABLE bans (
  id SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  issued TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:00',
  "moderatorId" INTEGER,
  message VARCHAR(60)
);

CREATE TABLE buddies (
  "userId" INTEGER NOT NULL,
  "buddyId" INTEGER NOT NULL,
  PRIMARY KEY ("userId", "buddyId")
);

CREATE TABLE cards (
  "userId" INTEGER NOT NULL,
  "cardId" INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  "memberQuantity" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("userId", "cardId")
);

CREATE TABLE furnitures (
  id SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "furnitureId" INTEGER NOT NULL,
  x SMALLINT NOT NULL DEFAULT 0,
  y SMALLINT NOT NULL DEFAULT 0,
  rotation SMALLINT NOT NULL DEFAULT 1,
  frame SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE furniture_inventories (
  "userId" INTEGER NOT NULL,
  "itemId" INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  PRIMARY KEY ("userId", "itemId")
);

CREATE TABLE igloos (
  "userId" INTEGER PRIMARY KEY,
  type INTEGER NOT NULL DEFAULT 1,
  flooring INTEGER NOT NULL DEFAULT 0,
  music INTEGER NOT NULL DEFAULT 0,
  location INTEGER NOT NULL DEFAULT 1,
  locked BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE igloo_inventories (
  "userId" INTEGER NOT NULL,
  "iglooId" INTEGER NOT NULL,
  PRIMARY KEY ("userId", "iglooId")
);

CREATE TABLE ignores (
  "userId" INTEGER NOT NULL,
  "ignoreId" INTEGER NOT NULL,
  PRIMARY KEY ("userId", "ignoreId")
);

CREATE TABLE inventories (
  "userId" INTEGER NOT NULL,
  "itemId" INTEGER NOT NULL,
  PRIMARY KEY ("userId", "itemId")
);

CREATE TABLE pets (
  id SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "typeId" INTEGER NOT NULL,
  name VARCHAR(12) NOT NULL,
  "adoptionDate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  energy SMALLINT NOT NULL DEFAULT 100,
  health SMALLINT NOT NULL DEFAULT 100,
  rest SMALLINT NOT NULL DEFAULT 100,
  "feedPostcardId" INTEGER
);

CREATE TABLE postcards (
  id SERIAL PRIMARY KEY,
  "userId" INTEGER NOT NULL,
  "senderId" INTEGER,
  "postcardId" INTEGER NOT NULL,
  "sendDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  details VARCHAR(255),
  "hasRead" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(12) NOT NULL UNIQUE,
  email VARCHAR(254),
  password CHAR(60) NOT NULL,
  "loginKey" TEXT,
  rank SMALLINT NOT NULL DEFAULT 1,
  "permaBan" BOOLEAN NOT NULL DEFAULT FALSE,
  "joinTime" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  coins INTEGER NOT NULL DEFAULT 500,
  head INTEGER NOT NULL DEFAULT 0,
  face INTEGER NOT NULL DEFAULT 0,
  neck INTEGER NOT NULL DEFAULT 0,
  body INTEGER NOT NULL DEFAULT 0,
  hand INTEGER NOT NULL DEFAULT 0,
  feet INTEGER NOT NULL DEFAULT 0,
  color INTEGER NOT NULL DEFAULT 1,
  photo INTEGER NOT NULL DEFAULT 0,
  flag INTEGER NOT NULL DEFAULT 0,
  "ninjaRank" SMALLINT NOT NULL DEFAULT 0,
  "ninjaProgress" SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE worlds (
  id VARCHAR(100) PRIMARY KEY,
  population SMALLINT NOT NULL DEFAULT 0
);

INSERT INTO worlds (id, population) VALUES
('Blizzard', 0);

ALTER TABLE auth_tokens
  ADD CONSTRAINT auth_tokens_user FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE bans
  ADD CONSTRAINT bans_user FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT bans_moderator FOREIGN KEY ("moderatorId") REFERENCES users(id) ON DELETE SET NULL ON UPDATE SET NULL;
ALTER TABLE buddies
  ADD CONSTRAINT buddies_user FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT buddies_buddy FOREIGN KEY ("buddyId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE cards
  ADD CONSTRAINT cards_user FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE furnitures
  ADD CONSTRAINT furnitures_user FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE furniture_inventories
  ADD CONSTRAINT furniture_inventories_user FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE igloos
  ADD CONSTRAINT igloos_user FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE igloo_inventories
  ADD CONSTRAINT igloo_inventories_user FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ignores
  ADD CONSTRAINT ignores_user FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT ignores_ignore FOREIGN KEY ("ignoreId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE inventories
  ADD CONSTRAINT inventories_user FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE pets
  ADD CONSTRAINT pets_user FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT pets_feedpostcard FOREIGN KEY ("feedPostcardId") REFERENCES postcards(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE postcards
  ADD CONSTRAINT postcards_user FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT postcards_sender FOREIGN KEY ("senderId") REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE OR REPLACE FUNCTION trigger_users_insert() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO igloos ("userId") VALUES (NEW.id);
    INSERT INTO inventories ("userId", "itemId") VALUES (NEW.id, NEW.color);
    INSERT INTO postcards ("userId", "postcardId") VALUES (NEW.id, 125);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_users_insert
AFTER INSERT ON users
FOR EACH ROW EXECUTE PROCEDURE trigger_users_insert();

COMMIT;
